# Gradle settings
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Game, mappings and loader versions
parchment_minecraft_version=1.21.3
parchment_mappings_version=2024.12.07
minecraft_version=1.21.3
minecraft_version_range=[1.21.3, 1.21.4)
neo_version=21.3.65
neo_version_range=[21.3,)
loader_version_range=[4,)

# Mod Properties
mod_id=immersive_portals
mod_name=Immersive Portals (for Neo)
mod_license=Apache-2.0
# don't forget to change changelog.md after bumping version
mod_version=6.0.6
mod_group_id=qouteall
mod_authors=qouteall, Nick1st, Other Contributors (see GitHub)
mod_description=See through portals and travel between dimensions seamlessly.

modmenu_version=11.0.1
cloth_config_version=15.0.130
sodium_path=maven.modrinth:sodium:mc1.21-0.5.11
iris_path=maven.modrinth:iris:1.7.3+1.21
gravity_changer_version=cd4e3377
dimlib_version=v1.1.0-mc1.21.1
enable_sodium=true
enable_iris=false
enable_pehkui=false
enable_gravity_changer=false
enable_test_mod=false
enable_geckolib=false

# don't forget to update this if branch changes
git_branch=1.21.3

# Pack version - this changes each minecraft release, in general.
pack_format_number=18
# A URL to refer people to when problems occur with this mod
issue_tracker_url=https://github.com/iPortalTeam/ImmersivePortalsModForNeo/issues